// <auto-generated />
using System;
using GuvenliBelgeAnonimlestirmeSistemi.WebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuvenliBelgeAnonimlestirmeSistemi.WebApi.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20250401212431_imagejsonalanısildim")]
    partial class imagejsonalanısildim
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Article", b =>
                {
                    b.Property<int>("MakaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MakaleId"));

                    b.Property<string>("AnonimPdfFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EnSonYapilanIsleminTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedInfoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HakemDegerlendirmesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakaleDurumu")
                        .HasColumnType("int");

                    b.Property<DateTime>("MakaleYuklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdfFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<string>("SonucPdfFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TakipNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YazarEPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MakaleId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.ArticleField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FieldTopicId")
                        .HasColumnType("int");

                    b.Property<int>("MakaleId")
                        .HasColumnType("int");

                    b.Property<double>("Skor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FieldTopicId");

                    b.HasIndex("MakaleId");

                    b.ToTable("ArticleFields");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Editor", b =>
                {
                    b.Property<int>("EditorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EditorId"));

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EditorId");

                    b.ToTable("Editors");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.FieldTopic", b =>
                {
                    b.Property<int>("FieldTopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldTopicId"));

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("KonuAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KonuAdiEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldTopicId");

                    b.HasIndex("FieldId");

                    b.ToTable("FieldTopics");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("LogDetayi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MakaleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("islemZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("LogId");

                    b.HasIndex("MakaleId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("MakaleId")
                        .HasColumnType("int");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SendRol")
                        .HasColumnType("int");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("MakaleId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Reviewer", b =>
                {
                    b.Property<int>("ReviewerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewerId"));

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewerId");

                    b.ToTable("Reviewers");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.ReviewerFieldTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FieldTopicId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FieldTopicId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("ReviewerFieldTopics");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Article", b =>
                {
                    b.HasOne("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Reviewer", "Hakem")
                        .WithMany("Makaleler")
                        .HasForeignKey("ReviewerId");

                    b.Navigation("Hakem");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.ArticleField", b =>
                {
                    b.HasOne("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.FieldTopic", "AltKonular")
                        .WithMany()
                        .HasForeignKey("FieldTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Article", "Makale")
                        .WithMany("ArticleFields")
                        .HasForeignKey("MakaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AltKonular");

                    b.Navigation("Makale");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.FieldTopic", b =>
                {
                    b.HasOne("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Field", "Alan")
                        .WithMany("AlanAltBasliklari")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alan");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Log", b =>
                {
                    b.HasOne("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Article", "Makale")
                        .WithMany()
                        .HasForeignKey("MakaleId");

                    b.Navigation("Makale");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Message", b =>
                {
                    b.HasOne("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Article", "Makale")
                        .WithMany("Messages")
                        .HasForeignKey("MakaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makale");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.ReviewerFieldTopic", b =>
                {
                    b.HasOne("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.FieldTopic", "AltKonular")
                        .WithMany()
                        .HasForeignKey("FieldTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Reviewer", "Reviewer")
                        .WithMany("HakemIlgiAlanlari")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AltKonular");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Article", b =>
                {
                    b.Navigation("ArticleFields");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Field", b =>
                {
                    b.Navigation("AlanAltBasliklari");
                });

            modelBuilder.Entity("GuvenliBelgeAnonimlestirmeSistemi.WebApi.Entity.Reviewer", b =>
                {
                    b.Navigation("HakemIlgiAlanlari");

                    b.Navigation("Makaleler");
                });
#pragma warning restore 612, 618
        }
    }
}
